from strategy.unified_base_strategy import UnifiedBaseStrategy
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
历史买点自动策略生成系统 - 集成示例

演示完整的策略生成流程：
1. 从历史买点数据生成策略
2. 执行双向验证
3. 性能优化和部署

使用说明：
- 输入历史买点数据（股票代码 + 买点日期）
- 系统自动分析技术特征并生成策略
- 通过双向验证确保策略有效性
- 提供性能优化建议
"""

import os
import sys
import time
import logging
import pandas as pd
import numpy as np
from typing import Dict, List, Any, Optional, Tuple
from datetime import datetime, timedelta
import argparse
import json

# 添加项目根目录到路径
project_root = os.path.dirname(os.path.abspath(__file__))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from strategy.historical_buypoint_strategy_generator import (
    HistoricalBuyPointStrategyGenerator, PatternExtractionMethod,
    StrategyGenerationMode, AutoGeneratedStrategy
)
from strategy.strategy_bidirectional_validation_engine import (
    StrategyBidirectionalValidationEngine, StrategyValidationReport
)
from utils.logger import get_logger, get_service
from db.interfaces.data_access_interface import DataAccessInterface

logger = get_logger(__name__)

class HistoricalBuyPointStrategySystem:
    """
    历史买点自动策略生成系统

    集成完整的策略生成、验证和优化流程
    """

    def __init__(self):
        """初始化系统"""
        self.logger = get_logger(__name__)

        # 核心组件
        self.strategy_generator = HistoricalBuyPointStrategyGenerator()
        self.validation_engine = StrategyBidirectionalValidationEngine()
        self.data_access = get_service(DataAccessInterface)

        # 系统配置
        self.config = {
            'min_buypoints_required': 10,     # 最少需要的历史买点数量
            'validation_stock_pool_size': 1000, # 验证股票池大小
            'performance_threshold': 70.0,      # 性能阈值
            'max_optimization_iterations': 3    # 最大优化迭代次数
        }

        self.logger.info("历史买点自动策略生成系统初始化完成")

    def generate_strategy_from_historical_data(self,
                                             buypoint_data: List[Tuple[str, str]],
                                             strategy_name: str = None,
                                             generation_config: Optional[Dict[str, Any]] = None) -> AutoGeneratedStrategy:
        """
        从历史买点数据生成策略

        Args:
            buypoint_data: [(股票代码, 买点日期), ...] 列表
            strategy_name: 策略名称
            generation_config: 生成配置

        Returns:
            AutoGeneratedStrategy: 生成的策略对象
        """
        if len(buypoint_data) < self.config['min_buypoints_required']:
            raise ValueError(f"历史买点数据不足，至少需要 {self.config['min_buypoints_required']} 个买点")

        strategy_name = strategy_name or f"HistBP_Strategy_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        self.logger.info(f"开始生成策略: {strategy_name}")
        self.logger.info(f"历史买点数量: {len(buypoint_data)}")

        # 应用生成配置
        if generation_config:
            self._apply_generation_config(generation_config)

        # 生成策略
        generated_strategy = self.strategy_generator.generate_strategy_from_buypoints(
            buypoint_data=buypoint_data,
            strategy_name=strategy_name,
            min_pattern_frequency=generation_config.get('min_pattern_frequency', 3),
            min_success_rate=generation_config.get('min_success_rate', 0.6)
        )

        # 创建可执行策略
        executable_strategy = self.strategy_generator.create_executable_strategy(generated_strategy)

        self.logger.info(f"策略生成完成: {strategy_name}")

        return executable_strategy

    def validate_strategy_performance(self,
                                    strategy: AutoGeneratedStrategy,
                                    validation_config: Optional[Dict[str, Any]] = None) -> StrategyValidationReport:
        """
        验证策略性能

        Args:
            strategy: 待验证的策略
            validation_config: 验证配置

        Returns:
            StrategyValidationReport: 验证报告
        """
        self.logger.info(f"开始验证策略性能: {strategy.name}")

        # 准备验证股票池
        test_universe = self._prepare_validation_universe(
            pool_size=validation_config.get('pool_size', self.config['validation_stock_pool_size'])
            if validation_config else self.config['validation_stock_pool_size']
        )

        # 执行双向验证
        validation_report = self.validation_engine.validate_strategy(
            strategy=strategy,
            test_universe=test_universe,
            validation_date=validation_config.get('validation_date') if validation_config else None,
            validation_period_days=validation_config.get('validation_period_days', 30)
                                 if validation_config else 30
        )

        self.logger.info(f"策略验证完成: {validation_report.overall_result.value}, "
                        f"综合评分: {validation_report.overall_score:.2f}")

        return validation_report

    def optimize_strategy_iteratively(self,
                                    buypoint_data: List[Tuple[str, str]],
                                    strategy_name: str = None,
                                    optimization_config: Optional[Dict[str, Any]] = None) -> Tuple[AutoGeneratedStrategy, StrategyValidationReport]:
        """
        迭代优化策略

        Args:
            buypoint_data: 历史买点数据
            strategy_name: 策略名称
            optimization_config: 优化配置

        Returns:
            Tuple[AutoGeneratedStrategy, StrategyValidationReport]: (最优策略, 最终验证报告)
        """
        max_iterations = optimization_config.get('max_iterations', self.config['max_optimization_iterations']) \
                        if optimization_config else self.config['max_optimization_iterations']

        target_performance = optimization_config.get('target_performance', self.config['performance_threshold']) \
                           if optimization_config else self.config['performance_threshold']

        self.logger.info(f"开始迭代优化策略，最大迭代次数: {max_iterations}")

        best_strategy = None
        best_report = None
        best_score = 0.0

        for iteration in range(max_iterations):
            self.logger.info(f"优化迭代 {iteration + 1}/{max_iterations}")

            try:
                # 根据迭代次数调整生成参数
                generation_config = self._get_iteration_config(iteration, optimization_config)

                # 生成策略
                strategy = self.generate_strategy_from_historical_data(
                    buypoint_data=buypoint_data,
                    strategy_name=f"{strategy_name}_iter{iteration+1}" if strategy_name else None,
                    generation_config=generation_config
                )

                # 验证策略
                validation_report = self.validate_strategy_performance(strategy)

                # 检查是否是最佳策略
                if validation_report.overall_score > best_score:
                    best_strategy = strategy
                    best_report = validation_report
                    best_score = validation_report.overall_score

                    self.logger.info(f"发现更好的策略，评分: {best_score:.2f}")

                # 如果达到目标性能，提前结束
                if validation_report.overall_score >= target_performance:
                    self.logger.info(f"达到目标性能 {target_performance}，提前结束优化")
                    break

            except Exception as e:
                self.logger.warning(f"优化迭代 {iteration + 1} 失败: {e}")
                continue

        if best_strategy is None:
            raise RuntimeError("策略优化失败，未能生成有效策略")

        self.logger.info(f"策略优化完成，最佳评分: {best_score:.2f}")
        return best_strategy, best_report

    def _apply_generation_config(self, config: Dict[str, Any]) -> None:
        """应用生成配置"""
        if 'pattern_method' in config:
            method_map = {
                'statistical': PatternExtractionMethod.STATISTICAL_ANALYSIS,
                'clustering': PatternExtractionMethod.CLUSTERING,
                'frequent': PatternExtractionMethod.FREQUENT_PATTERNS,
                'ml': PatternExtractionMethod.MACHINE_LEARNING,
                'hybrid': PatternExtractionMethod.HYBRID
            }
            self.strategy_generator.pattern_method = method_map.get(config['pattern_method'], PatternExtractionMethod.HYBRID)

        if 'generation_mode' in config:
            mode_map = {
                'conservative': StrategyGenerationMode.CONSERVATIVE,
                'balanced': StrategyGenerationMode.BALANCED,
                'aggressive': StrategyGenerationMode.AGGRESSIVE,
                'adaptive': StrategyGenerationMode.ADAPTIVE
            }
            self.strategy_generator.generation_mode = mode_map.get(config['generation_mode'], StrategyGenerationMode.BALANCED)

    def _prepare_validation_universe(self, pool_size: int) -> List[str]:
        """准备验证股票池"""
        try:
            # 获取活跃股票列表
            # 这里应该调用实际的数据接口获取股票列表
            # 简化实现：生成模拟股票代码
            universe = []

            # 生成模拟的A股代码
            for i in range(1, pool_size + 1):
                if i <= 999:
                    code = f"00{i:04d}"  # 深市主板
                elif i <= 1999:
                    code = f"30{i-999:04d}"  # 创业板
                else:
                    code = f"60{i-1999:04d}"  # 沪市主板
                universe.append(code)

            self.logger.info(f"准备验证股票池，大小: {len(universe)}")
            return universe[:pool_size]

        except Exception as e:
            self.logger.warning(f"准备验证股票池失败: {e}")
            # 返回默认的小规模股票池
            return ["000001", "000002", "600000", "600036", "000858"]

    def _get_iteration_config(self, iteration: int, base_config: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """获取迭代配置"""
        base_config = base_config or {}

        # 根据迭代次数调整参数
        configs = [
            {**base_config, 'generation_mode': 'conservative', 'min_pattern_frequency': 5},
            {**base_config, 'generation_mode': 'balanced', 'min_pattern_frequency': 3},
            {**base_config, 'generation_mode': 'aggressive', 'min_pattern_frequency': 2},
        ]

        return configs[min(iteration, len(configs) - 1)]

    def save_strategy_and_report(self,
                               strategy: AutoGeneratedStrategy,
                               validation_report: StrategyValidationReport,
                               output_dir: str) -> Dict[str, str]:
        """
        保存策略和报告

        Args:
            strategy: 策略对象
            validation_report: 验证报告
            output_dir: 输出目录

        Returns:
            Dict[str, str]: 保存的文件路径
        """
        os.makedirs(output_dir, exist_ok=True)

        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

        # 保存策略
        strategy_file = os.path.join(output_dir, f"strategy_{timestamp}.pkl")
        self.strategy_generator.save_strategy(strategy.generated_strategy, strategy_file)

        # 保存验证报告
        report_file = os.path.join(output_dir, f"validation_report_{timestamp}.json")
        self.validation_engine.save_validation_report(validation_report, report_file)

        # 生成摘要报告
        summary_file = os.path.join(output_dir, f"summary_report_{timestamp}.txt")
        summary_text = self.validation_engine.generate_validation_summary_report(validation_report)
        with open(summary_file, 'w', encoding='utf-8') as f:
            f.write(summary_text)

        # 生成策略信息
        info_file = os.path.join(output_dir, f"strategy_info_{timestamp}.json")
        strategy_info = strategy.get_strategy_info()
        with open(info_file, 'w', encoding='utf-8') as f:
            json.dump(strategy_info, f, indent=2, ensure_ascii=False, default=str)

        file_paths = {
            'strategy': strategy_file,
            'validation_report': report_file,
            'summary': summary_file,
            'strategy_info': info_file
        }

        self.logger.info(f"策略和报告已保存到: {output_dir}")
        return file_paths


def main():
    """主函数 - 命令行接口"""
    parser = argparse.ArgumentParser(description="历史买点自动策略生成系统")
    parser.add_argument('--input', '-i', required=True, help='历史买点数据文件路径（CSV格式）')
    parser.add_argument('--output', '-o', default='./output', help='输出目录')
    parser.add_argument('--strategy-name', '-n', help='策略名称')
    parser.add_argument('--optimize', action='store_true', help='启用迭代优化')
    parser.add_argument('--validation-only', action='store_true', help='仅执行验证（需要提供策略文件）')
    parser.add_argument('--strategy-file', help='已存在的策略文件路径')
    parser.add_argument('--config', help='配置文件路径（JSON格式）')

    args = parser.parse_args()

    # 初始化系统
    system = HistoricalBuyPointStrategySystem()

    try:
        # 加载配置
        config = {}
        if args.config and os.path.exists(args.config):
            with open(args.config, 'r', encoding='utf-8') as f:
                config = json.load(f)

        if args.validation_only:
            # 仅验证模式
            if not args.strategy_file or not os.path.exists(args.strategy_file):
                raise ValueError("验证模式需要提供有效的策略文件路径")

            strategy = system.strategy_generator.load_strategy(args.strategy_file)
            executable_strategy = system.strategy_generator.create_executable_strategy(strategy)
            validation_report = system.validate_strategy_performance(
                executable_strategy,
                config.get('validation', {})
            )

            # 保存验证报告
            file_paths = system.save_strategy_and_report(executable_strategy, validation_report, args.output)
            print(f"验证报告已保存: {file_paths['validation_report']}")

        else:
            # 完整生成模式

            # 读取历史买点数据
            if not os.path.exists(args.input):
                raise FileNotFoundError(f"输入文件不存在: {args.input}")

            buypoint_df = pd.read_csv(args.input)
            if 'stock_code' not in buypoint_df.columns or 'buypoint_date' not in buypoint_df.columns:
                raise ValueError("输入文件必须包含 'stock_code' 和 'buypoint_date' 列")

            buypoint_data = [(row['stock_code'], row['buypoint_date'])
                           for _, row in buypoint_df.iterrows()]

            print(f"加载历史买点数据: {len(buypoint_data)} 个")

            if args.optimize:
                # 迭代优化模式
                strategy, validation_report = system.optimize_strategy_iteratively(
                    buypoint_data=buypoint_data,
                    strategy_name=args.strategy_name,
                    optimization_config=config.get('optimization', {})
                )
            else:
                # 单次生成模式
                strategy = system.generate_strategy_from_historical_data(
                    buypoint_data=buypoint_data,
                    strategy_name=args.strategy_name,
                    generation_config=config.get('generation', {})
                )

                validation_report = system.validate_strategy_performance(
                    strategy,
                    config.get('validation', {})
                )

            # 保存结果
            file_paths = system.save_strategy_and_report(strategy, validation_report, args.output)

            print("策略生成完成！")
            print(f"策略文件: {file_paths['strategy']}")
            print(f"验证报告: {file_paths['validation_report']}")
            print(f"摘要报告: {file_paths['summary']}")
            print(f"\n{system.validation_engine.generate_validation_summary_report(validation_report)}")

    except Exception as e:
        logger.error(f"系统执行失败: {e}")
        print(f"错误: {e}")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())