#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
策略双向验证引擎

实现策略→选股→买点验证的闭环验证，确保策略的有效性和可靠性

验证流程：
1. 策略执行选股
2. 对选出的股票进行买点检测
3. 验证买点质量和预期表现
4. 生成验证报告和优化建议
"""

import os
import time
import numpy as np
import pandas as pd
from typing import Dict, List, Any, Optional, Tuple, Union
from datetime import datetime, timedelta
from dataclasses import dataclass, asdict
from enum import Enum
import json

from utils.dependency_injection import get_logger, get_service
from utils.decorators import performance_monitor, exception_handler
from db.interfaces.data_access_interface import DataAccessInterface
from strategy.historical_buypoint_strategy_generator import (
    HistoricalBuyPointStrategyGenerator, AutoGeneratedStrategy,
    GeneratedStrategy, BuyPointFeature
)
from analysis.buypoints.enhanced_buypoint_detector import (
    EnhancedBuyPointDetector, BuyPointSignal, BuyPointType, BuyPointQuality
)

logger = get_logger(__name__)

class ValidationResult(Enum):
    """验证结果"""
    PASSED = "通过"
    WARNING = "警告"
    FAILED = "失败"

@dataclass
class BuyPointValidation:
    """买点验证结果"""
    stock_code: str
    validation_date: str
    detected_buypoints: List[BuyPointSignal]
    quality_score: float  # 0-100
    confidence_level: float  # 0-1
    risk_assessment: Dict[str, Any]
    validation_result: ValidationResult
    validation_details: Dict[str, Any]

@dataclass
class StrategyValidationReport:
    """策略验证报告"""
    strategy_name: str
    validation_id: str
    validation_date: str

    # 选股结果
    selected_stocks: pd.DataFrame
    selection_summary: Dict[str, Any]

    # 买点验证结果
    buypoint_validations: List[BuyPointValidation]
    validation_summary: Dict[str, Any]

    # 整体评估
    overall_score: float
    overall_result: ValidationResult

    # 性能指标
    performance_metrics: Dict[str, float]

    # 优化建议
    optimization_suggestions: List[str]

    # 元数据
    validation_metadata: Dict[str, Any]

class StrategyBidirectionalValidationEngine:
    """
    策略双向验证引擎

    核心功能：
    1. 策略执行验证：测试策略的选股能力
    2. 买点质量验证：检验选出股票的买点质量
    3. 预期表现验证：评估策略的预期收益和风险
    4. 策略优化建议：基于验证结果提供优化建议
    """

    def __init__(self):
        """初始化双向验证系统"""
        self.logger = get_logger(__name__)
        self.data_access = get_service(DataAccessInterface)
        self.buypoint_detector = EnhancedBuyPointDetector()

        # 验证阈值配置
        self.validation_thresholds = {
            'min_buypoint_quality': 60.0,  # 最小买点质量分数
            'min_confidence_level': 0.5,   # 最小置信水平
            'min_success_rate': 0.4,       # 最小成功率
            'max_risk_score': 0.7,         # 最大风险评分
            'min_selected_stocks': 5,      # 最小选股数量
            'max_selected_stocks': 100     # 最大选股数量
        }

        self.logger.info("策略双向验证引擎初始化完成")

    @performance_monitor(threshold=30.0)
    @exception_handler(reraise=True)
    def validate_strategy(self,
                         strategy: AutoGeneratedStrategy,
                         test_universe: List[str],
                         validation_date: Optional[str] = None,
                         validation_period_days: int = 30) -> StrategyValidationReport:
        """
        完整的策略双向验证

        Args:
            strategy: 待验证的策略
            test_universe: 测试股票池
            validation_date: 验证日期，默认为最新交易日
            validation_period_days: 验证期间天数

        Returns:
            StrategyValidationReport: 验证报告
        """
        validation_id = f"validation_{int(time.time())}"

        if not validation_date:
            validation_date = self.data_access.get_latest_trading_date()

        self.logger.info(f"开始策略双向验证 [{validation_id}]: {strategy.name}")

        # 第一步：策略执行 - 选股
        selected_stocks = self._execute_strategy_selection(strategy, test_universe, validation_date)

        # 第二步：买点验证 - 对选出的股票进行买点检测
        buypoint_validations = self._validate_buypoints(selected_stocks, validation_date, validation_period_days)

        # 第三步：综合评估
        validation_report = self._generate_validation_report(
            strategy, validation_id, validation_date,
            selected_stocks, buypoint_validations,
            test_universe
        )

        self.logger.info(f"策略验证完成: {validation_report.overall_result.value}, "
                        f"整体评分: {validation_report.overall_score:.2f}")

        return validation_report

    def _execute_strategy_selection(self,
                                  strategy: AutoGeneratedStrategy,
                                  test_universe: List[str],
                                  validation_date: str) -> pd.DataFrame:
        """
        执行策略选股

        Args:
            strategy: 策略对象
            test_universe: 测试股票池
            validation_date: 验证日期

        Returns:
            pd.DataFrame: 选股结果
        """
        self.logger.info(f"执行策略选股，股票池大小: {len(test_universe)}")

        try:
            # 计算开始日期（验证日期前90天，确保有足够的数据计算技术指标）
            validation_dt = datetime.strptime(validation_date, '%Y-%m-%d')
            start_date = (validation_dt - timedelta(days=90)).strftime('%Y-%m-%d')

            # 执行策略选股
            selected_stocks = strategy.execute(
                universe=test_universe,
                start_date=start_date,
                end_date=validation_date
            )

            self.logger.info(f"策略选股完成，选出 {len(selected_stocks)} 只股票")
            return selected_stocks

        except Exception as e:
            self.logger.error(f"策略选股失败: {e}")
            return pd.DataFrame()

    def _validate_buypoints(self,
                          selected_stocks: pd.DataFrame,
                          validation_date: str,
                          validation_period_days: int) -> List[BuyPointValidation]:
        """
        验证选出股票的买点质量

        Args:
            selected_stocks: 选出的股票
            validation_date: 验证日期
            validation_period_days: 验证期间

        Returns:
            List[BuyPointValidation]: 买点验证结果列表
        """
        validations = []

        if selected_stocks.empty:
            self.logger.warning("没有选出股票，跳过买点验证")
            return validations

        self.logger.info(f"开始买点验证，股票数量: {len(selected_stocks)}")

        # 计算验证期间的结束日期
        validation_dt = datetime.strptime(validation_date, '%Y-%m-%d')
        end_date = (validation_dt + timedelta(days=validation_period_days)).strftime('%Y-%m-%d')

        for _, stock_row in selected_stocks.iterrows():
            stock_code = stock_row['code']

            try:
                validation = self._validate_single_stock_buypoint(
                    stock_code, validation_date, end_date
                )
                validations.append(validation)

            except Exception as e:
                self.logger.warning(f"股票买点验证失败 {stock_code}: {e}")
                # 创建失败的验证记录
                failed_validation = BuyPointValidation(
                    stock_code=stock_code,
                    validation_date=validation_date,
                    detected_buypoints=[],
                    quality_score=0.0,
                    confidence_level=0.0,
                    risk_assessment={'error': str(e)},
                    validation_result=ValidationResult.FAILED,
                    validation_details={'error': str(e)}
                )
                validations.append(failed_validation)

        self.logger.info(f"买点验证完成，验证了 {len(validations)} 只股票")
        return validations

    def _validate_single_stock_buypoint(self,
                                      stock_code: str,
                                      start_date: str,
                                      end_date: str) -> BuyPointValidation:
        """
        验证单只股票的买点

        Args:
            stock_code: 股票代码
            start_date: 开始日期
            end_date: 结束日期

        Returns:
            BuyPointValidation: 验证结果
        """
        # 获取股票数据
        stock_data = self.data_access.get_stock_data(stock_code, start_date, end_date)

        if stock_data.empty:
            raise ValueError(f"无法获取股票数据: {stock_code}")

        # 检测买点
        detected_buypoints = self._detect_buypoints_in_period(stock_code, stock_data)

        # 计算质量评分
        quality_score = self._calculate_buypoint_quality_score(detected_buypoints, stock_data)

        # 计算置信水平
        confidence_level = self._calculate_confidence_level(detected_buypoints)

        # 风险评估
        risk_assessment = self._assess_risk(stock_code, stock_data, detected_buypoints)

        # 确定验证结果
        validation_result = self._determine_validation_result(quality_score, confidence_level, risk_assessment)

        # 详细信息
        validation_details = {
            'buypoint_count': len(detected_buypoints),
            'avg_quality_score': quality_score,
            'data_period': f"{start_date} to {end_date}",
            'analysis_date': datetime.now().isoformat()
        }

        return BuyPointValidation(
            stock_code=stock_code,
            validation_date=start_date,
            detected_buypoints=detected_buypoints,
            quality_score=quality_score,
            confidence_level=confidence_level,
            risk_assessment=risk_assessment,
            validation_result=validation_result,
            validation_details=validation_details
        )

    def _detect_buypoints_in_period(self,
                                  stock_code: str,
                                  stock_data: pd.DataFrame) -> List[BuyPointSignal]:
        """在指定期间内检测买点"""
        buypoints = []

        try:
            # 使用买点检测器检测买点
            # 这里可以调用enhanced_buypoint_detector的相关方法
            # 简化实现：基于技术指标检测简单买点

            for i in range(1, len(stock_data)):
                current_row = stock_data.iloc[i]
                prev_row = stock_data.iloc[i-1]

                # 简单的买点检测逻辑：放量上涨
                volume_ratio = current_row['volume'] / prev_row['volume'] if prev_row['volume'] > 0 else 1
                price_change = (current_row['close'] - prev_row['close']) / prev_row['close']

                if volume_ratio > 1.5 and price_change > 0.03:  # 放量上涨3%以上
                    buypoint = BuyPointSignal(
                        signal_id=f"bp_{stock_code}_{current_row['date']}",
                        stock_code=stock_code,
                        detection_date=current_row['date'],
                        buypoint_type=BuyPointType.VOLUME_BREAKOUT,
                        quality=BuyPointQuality.GOOD,
                        confidence=min(0.9, volume_ratio / 3.0),
                        score=min(100, 50 + price_change * 1000),
                        price=current_row['close'],
                        volume=current_row['volume'],
                        technical_indicators={'volume_ratio': volume_ratio, 'price_change': price_change},
                        pattern_analysis={'pattern': 'volume_breakout'},
                        risk_assessment={'volatility': abs(price_change)},
                        recommendations=['考虑买入', '设置止损']
                    )
                    buypoints.append(buypoint)

        except Exception as e:
            self.logger.debug(f"买点检测失败 {stock_code}: {e}")

        return buypoints

    def _calculate_buypoint_quality_score(self,
                                        buypoints: List[BuyPointSignal],
                                        stock_data: pd.DataFrame) -> float:
        """计算买点质量评分"""
        if not buypoints:
            return 0.0

        # 计算买点的平均质量分数
        total_score = sum(bp.score for bp in buypoints)
        avg_score = total_score / len(buypoints)

        # 考虑买点数量的影响（适量的买点数量更好）
        count_factor = min(1.0, len(buypoints) / 3.0)  # 理想情况是3个左右买点

        return min(100.0, avg_score * count_factor)

    def _calculate_confidence_level(self, buypoints: List[BuyPointSignal]) -> float:
        """计算置信水平"""
        if not buypoints:
            return 0.0

        # 计算买点的平均置信度
        avg_confidence = sum(bp.confidence for bp in buypoints) / len(buypoints)

        # 考虑买点一致性的影响
        confidence_values = [bp.confidence for bp in buypoints]
        consistency = 1.0 - np.std(confidence_values) if len(confidence_values) > 1 else 1.0

        return avg_confidence * consistency

    def _assess_risk(self,
                   stock_code: str,
                   stock_data: pd.DataFrame,
                   buypoints: List[BuyPointSignal]) -> Dict[str, Any]:
        """风险评估"""
        risk_assessment = {}

        try:
            # 价格波动性
            returns = stock_data['close'].pct_change().dropna()
            volatility = returns.std()
            risk_assessment['volatility'] = float(volatility)

            # 买点风险
            if buypoints:
                avg_buypoint_risk = np.mean([
                    bp.risk_assessment.get('volatility', 0.1) for bp in buypoints
                ])
                risk_assessment['buypoint_risk'] = avg_buypoint_risk
            else:
                risk_assessment['buypoint_risk'] = 1.0  # 没有买点，风险最高

            # 综合风险评分
            risk_score = (risk_assessment['volatility'] * 0.6 +
                         risk_assessment['buypoint_risk'] * 0.4)
            risk_assessment['overall_risk'] = min(1.0, risk_score)

        except Exception as e:
            self.logger.debug(f"风险评估失败 {stock_code}: {e}")
            risk_assessment['overall_risk'] = 0.8  # 默认较高风险

        return risk_assessment

    def _determine_validation_result(self,
                                   quality_score: float,
                                   confidence_level: float,
                                   risk_assessment: Dict[str, Any]) -> ValidationResult:
        """确定验证结果"""
        overall_risk = risk_assessment.get('overall_risk', 0.8)

        # 验证逻辑
        if (quality_score >= self.validation_thresholds['min_buypoint_quality'] and
            confidence_level >= self.validation_thresholds['min_confidence_level'] and
            overall_risk <= self.validation_thresholds['max_risk_score']):
            return ValidationResult.PASSED
        elif (quality_score >= self.validation_thresholds['min_buypoint_quality'] * 0.8 and
              confidence_level >= self.validation_thresholds['min_confidence_level'] * 0.8):
            return ValidationResult.WARNING
        else:
            return ValidationResult.FAILED

    def _generate_validation_report(self,
                                  strategy: AutoGeneratedStrategy,
                                  validation_id: str,
                                  validation_date: str,
                                  selected_stocks: pd.DataFrame,
                                  buypoint_validations: List[BuyPointValidation],
                                  test_universe: List[str]) -> StrategyValidationReport:
        """生成验证报告"""

        # 选股摘要
        selection_summary = {
            'total_universe': len(test_universe),
            'selected_count': len(selected_stocks),
            'selection_rate': len(selected_stocks) / len(test_universe) if test_universe else 0.0,
            'avg_score': float(selected_stocks['score'].mean()) if not selected_stocks.empty else 0.0
        }

        # 买点验证摘要
        validation_summary = self._generate_validation_summary(buypoint_validations)

        # 计算整体评分和结果
        overall_score, overall_result = self._calculate_overall_assessment(
            selection_summary, validation_summary, buypoint_validations
        )

        # 性能指标
        performance_metrics = self._calculate_performance_metrics(selected_stocks, buypoint_validations)

        # 优化建议
        optimization_suggestions = self._generate_optimization_suggestions(
            strategy, selection_summary, validation_summary, buypoint_validations
        )

        return StrategyValidationReport(
            strategy_name=strategy.name,
            validation_id=validation_id,
            validation_date=validation_date,
            selected_stocks=selected_stocks,
            selection_summary=selection_summary,
            buypoint_validations=buypoint_validations,
            validation_summary=validation_summary,
            overall_score=overall_score,
            overall_result=overall_result,
            performance_metrics=performance_metrics,
            optimization_suggestions=optimization_suggestions,
            validation_metadata={
                'validation_time': datetime.now().isoformat(),
                'system_version': '1.0.0',
                'validation_thresholds': self.validation_thresholds
            }
        )

    def _generate_validation_summary(self, validations: List[BuyPointValidation]) -> Dict[str, Any]:
        """生成买点验证摘要"""
        if not validations:
            return {
                'total_validations': 0,
                'passed_count': 0,
                'warning_count': 0,
                'failed_count': 0,
                'avg_quality_score': 0.0,
                'avg_confidence_level': 0.0,
                'success_rate': 0.0
            }

        passed_count = sum(1 for v in validations if v.validation_result == ValidationResult.PASSED)
        warning_count = sum(1 for v in validations if v.validation_result == ValidationResult.WARNING)
        failed_count = sum(1 for v in validations if v.validation_result == ValidationResult.FAILED)

        avg_quality = np.mean([v.quality_score for v in validations])
        avg_confidence = np.mean([v.confidence_level for v in validations])
        success_rate = passed_count / len(validations)

        return {
            'total_validations': len(validations),
            'passed_count': passed_count,
            'warning_count': warning_count,
            'failed_count': failed_count,
            'avg_quality_score': float(avg_quality),
            'avg_confidence_level': float(avg_confidence),
            'success_rate': float(success_rate)
        }

    def _calculate_overall_assessment(self,
                                    selection_summary: Dict[str, Any],
                                    validation_summary: Dict[str, Any],
                                    validations: List[BuyPointValidation]) -> Tuple[float, ValidationResult]:
        """计算整体评估结果"""

        # 选股得分 (40%)
        selection_score = min(100.0, selection_summary['avg_score'])

        # 买点质量得分 (60%)
        validation_score = validation_summary['avg_quality_score']

        # 加权计算总分
        overall_score = selection_score * 0.4 + validation_score * 0.6

        # 根据成功率和整体分数确定结果
        success_rate = validation_summary['success_rate']

        if overall_score >= 75 and success_rate >= 0.6:
            overall_result = ValidationResult.PASSED
        elif overall_score >= 60 and success_rate >= 0.4:
            overall_result = ValidationResult.WARNING
        else:
            overall_result = ValidationResult.FAILED

        return overall_score, overall_result

    def _calculate_performance_metrics(self,
                                     selected_stocks: pd.DataFrame,
                                     validations: List[BuyPointValidation]) -> Dict[str, float]:
        """计算性能指标"""
        metrics = {}

        # 选股性能
        if not selected_stocks.empty:
            metrics['selection_efficiency'] = len(selected_stocks) / 1000.0  # 假设基准
            metrics['avg_selection_score'] = float(selected_stocks['score'].mean())
            metrics['score_std'] = float(selected_stocks['score'].std())

        # 买点检测性能
        if validations:
            total_buypoints = sum(len(v.detected_buypoints) for v in validations)
            metrics['buypoint_detection_rate'] = total_buypoints / len(validations)
            metrics['avg_buypoint_quality'] = np.mean([v.quality_score for v in validations])

            # 风险指标
            avg_risk = np.mean([
                v.risk_assessment.get('overall_risk', 0.5) for v in validations
            ])
            metrics['avg_risk_score'] = float(avg_risk)

        return metrics

    def _generate_optimization_suggestions(self,
                                         strategy: AutoGeneratedStrategy,
                                         selection_summary: Dict[str, Any],
                                         validation_summary: Dict[str, Any],
                                         validations: List[BuyPointValidation]) -> List[str]:
        """生成优化建议"""
        suggestions = []

        # 基于选股结果的建议
        if selection_summary['selection_rate'] < 0.02:  # 选股过少
            suggestions.append("建议降低选股条件的严格程度，增加候选股票数量")
        elif selection_summary['selection_rate'] > 0.2:  # 选股过多
            suggestions.append("建议提高选股条件的严格程度，提高选股质量")

        # 基于买点质量的建议
        if validation_summary['avg_quality_score'] < 60:
            suggestions.append("买点质量偏低，建议优化技术指标组合或调整参数阈值")

        # 基于成功率的建议
        if validation_summary['success_rate'] < 0.5:
            suggestions.append("验证成功率偏低，建议重新分析历史买点数据，优化模式识别算法")

        # 基于风险的建议
        high_risk_count = sum(1 for v in validations
                             if v.risk_assessment.get('overall_risk', 0) > 0.7)
        if high_risk_count > len(validations) * 0.5:
            suggestions.append("高风险股票比例较高，建议加强风险控制条件")

        # 基于模式多样性的建议
        pattern_count = len(strategy.generated_strategy.pattern_templates)
        if pattern_count < 3:
            suggestions.append("策略模式数量较少，建议增加更多历史买点数据以识别更丰富的模式")
        elif pattern_count > 10:
            suggestions.append("策略模式过多可能导致过拟合，建议简化模式或提高筛选标准")

        return suggestions

    def save_validation_report(self, report: StrategyValidationReport, filepath: str) -> None:
        """保存验证报告"""
        try:
            # 将DataFrame转换为可序列化的格式
            report_dict = asdict(report)
            report_dict['selected_stocks'] = report.selected_stocks.to_dict('records')

            # 处理复杂对象
            for i, validation in enumerate(report_dict['buypoint_validations']):
                validation['detected_buypoints'] = [
                    asdict(bp) for bp in report.buypoint_validations[i].detected_buypoints
                ]
                validation['validation_result'] = validation['validation_result'].value

            report_dict['overall_result'] = report.overall_result.value

            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(report_dict, f, indent=2, ensure_ascii=False, default=str)

            self.logger.info(f"验证报告已保存到: {filepath}")

        except Exception as e:
            self.logger.error(f"保存验证报告失败: {e}")
            raise

    def generate_validation_summary_report(self, report: StrategyValidationReport) -> str:
        """生成验证摘要报告文本"""
        summary = f"""
策略双向验证报告摘要
========================

策略信息：
- 策略名称: {report.strategy_name}
- 验证日期: {report.validation_date}
- 验证ID: {report.validation_id}

选股结果：
- 测试股票池: {report.selection_summary['total_universe']}只
- 选出股票: {report.selection_summary['selected_count']}只
- 选股率: {report.selection_summary['selection_rate']:.2%}
- 平均评分: {report.selection_summary['avg_score']:.2f}

买点验证：
- 验证股票: {report.validation_summary['total_validations']}只
- 通过验证: {report.validation_summary['passed_count']}只
- 警告: {report.validation_summary['warning_count']}只
- 失败: {report.validation_summary['failed_count']}只
- 成功率: {report.validation_summary['success_rate']:.2%}
- 平均质量: {report.validation_summary['avg_quality_score']:.2f}

整体评估：
- 综合评分: {report.overall_score:.2f}/100
- 验证结果: {report.overall_result.value}

性能指标：
"""

        for metric, value in report.performance_metrics.items():
            summary += f"- {metric}: {value:.3f}\n"

        summary += "\n优化建议：\n"
        for i, suggestion in enumerate(report.optimization_suggestions, 1):
            summary += f"{i}. {suggestion}\n"

        return summary